CREATE TABLE app_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(254) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  password_change_required BOOLEAN NOT NULL DEFAULT FALSE,
  temporary_password_expires_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT uq_app_users_email UNIQUE (email),
  CONSTRAINT chk_app_users_email_normalized
    CHECK (email = LOWER(TRIM(email))),
  CONSTRAINT chk_app_users_temporary_password_state
    CHECK (
      (password_change_required = TRUE AND temporary_password_expires_at IS NOT NULL)
      OR
      (password_change_required = FALSE AND temporary_password_expires_at IS NULL)
    )
);

CREATE TABLE IF NOT EXISTS projects (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id INTEGER NOT NULL,
title VARCHAR(20) NOT NULL,
description VARCHAR(200),
is_finished BOOLEAN NOT NULL DEFAULT false,
CONSTRAINT fk_projects_user
 FOREIGN KEY (user_id) REFERENCES app_users(id),
CONSTRAINT chk_projects_title_not_blank
 CHECK (TRIM(title) <> '')
);

CREATE TABLE IF NOT EXISTS task_groups (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
project_id INTEGER NOT NULL,
title VARCHAR(20) NOT NULL,
description VARCHAR(200),
is_finished BOOLEAN NOT NULL DEFAULT false,
FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE IF NOT EXISTS tasks (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
project_id INTEGER,
task_group_id INTEGER,
title VARCHAR(20) NOT NULL,
description VARCHAR(200),
estimated_minutes INTEGER NOT NULL,
created_at TIMESTAMP NOT NULL,
finished_at TIMESTAMP,
actual_minutes_cached INTEGER,
gap_minutes_cached INTEGER,
gap_rate_cached DOUBLE PRECISION,
FOREIGN KEY (project_id) REFERENCES projects(id),
FOREIGN KEY (task_group_id) REFERENCES task_groups(id),
CONSTRAINT chk_tasks_parent_xor
    CHECK (
      (project_id IS NOT NULL AND task_group_id IS NULL)
      OR
      (project_id IS NULL AND task_group_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS work_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id INTEGER NOT NULL,
  minutes INTEGER,
  started_at TIMESTAMP,
  ended_at TIMESTAMP,
  type VARCHAR(10) NOT NULL DEFAULT 'TIMER',
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  FOREIGN KEY (task_id) REFERENCES tasks(id),
  CONSTRAINT chk_work_sessions_time_order
    CHECK (
      ended_at IS NULL
      OR
      (started_at IS NOT NULL AND ended_at >= started_at)
    ),
  CONSTRAINT chk_work_sessions_type
    CHECK (type = 'TIMER' OR type = 'MANUAL')
);

CREATE TABLE IF NOT EXISTS memos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER,
  task_group_id INTEGER,
  task_id INTEGER,
  comment VARCHAR(1000),
  FOREIGN KEY (project_id) REFERENCES projects(id),
  FOREIGN KEY (task_group_id) REFERENCES task_groups(id),
  FOREIGN KEY (task_id) REFERENCES tasks(id),
  CONSTRAINT chk_memos_parent_xor
    CHECK (
      (project_id IS NOT NULL AND task_group_id IS NULL AND task_id IS NULL)
      OR
      (project_id IS NULL AND task_group_id IS NOT NULL AND task_id IS NULL)
      OR
      (project_id IS NULL AND task_group_id IS NULL AND task_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS project_item_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id INTEGER NOT NULL,
  task_id INTEGER,
  task_group_id INTEGER,
  position INTEGER NOT NULL,
  FOREIGN KEY (project_id) REFERENCES projects(id),
  FOREIGN KEY (task_id) REFERENCES tasks(id),
  FOREIGN KEY (task_group_id) REFERENCES task_groups(id),
  CONSTRAINT chk_project_item_orders_item_xor
    CHECK (
      (task_id IS NOT NULL AND task_group_id IS NULL)
      OR
      (task_id IS NULL AND task_group_id IS NOT NULL)
    ),
  CONSTRAINT chk_project_item_orders_position_positive
    CHECK (position >= 0),
  CONSTRAINT uq_project_item_orders_task UNIQUE (task_id),
  CONSTRAINT uq_project_item_orders_task_group UNIQUE (task_group_id),
  CONSTRAINT uq_project_item_orders_position
    UNIQUE (project_id, position)
);

CREATE TABLE IF NOT EXISTS task_group_item_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_group_id INTEGER NOT NULL,
  task_id INTEGER NOT NULL,
  position INTEGER NOT NULL,
  FOREIGN KEY (task_group_id) REFERENCES task_groups(id),
  FOREIGN KEY (task_id) REFERENCES tasks(id),
  CONSTRAINT chk_task_group_item_orders_position_positive
    CHECK (position >= 0),
  CONSTRAINT uq_task_group_item_orders_task UNIQUE (task_id),
  CONSTRAINT uq_task_group_item_orders_position
    UNIQUE (task_group_id, position)
);

CREATE INDEX idx_projects_user_id ON projects (user_id);
CREATE INDEX idx_task_groups_project_id ON task_groups (project_id);
CREATE INDEX idx_tasks_project_id ON tasks (project_id);
CREATE INDEX idx_tasks_task_group_id ON tasks (task_group_id);
CREATE INDEX idx_work_sessions_task_id ON work_sessions (task_id);
CREATE INDEX idx_memos_project_id_id ON memos (project_id, id);
CREATE INDEX idx_memos_task_group_id_id ON memos (task_group_id, id);
CREATE INDEX idx_memos_task_id_id ON memos (task_id, id);
CREATE INDEX idx_project_item_orders_project_id_position
  ON project_item_orders (project_id, position);
CREATE INDEX idx_task_group_item_orders_task_group_id_position
  ON task_group_item_orders (task_group_id, position);
