spring.application.name=tasktimetracker
# DB????
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# MyBatis????????
mybatis.configuration.map-underscore-to-camel-case=true
# ????????????????
server.servlet.context-path=/api
